version: "3"

services:
  db:
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    networks:
      - network
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_PASSWORD=i#@hhr&nQnJO
      - TZ=America/Sao_Paulo

  adminer:
    image: adminer
    depends_on:
      - db
    networks:
      - network
    ports:
      - 8080:8080

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    networks:
      - network
    ports:
      - 6379:6379

networks:
  network:
    driver: bridge
